# Generated by Django 4.2.4 on 2023-08-31 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Gender')),
                ('mobile_no', models.CharField(max_length=10, verbose_name='Mobile No')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Id')),
                ('date', models.DateField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='StudyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=200, null=True, verbose_name='School/College')),
                ('standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Standard Name')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Percentage %')),
                ('passing_year', models.DateField(blank=True, null=True, verbose_name='Passing Year')),
                ('upload_documents', models.FileField(blank=True, null=True, upload_to='documents')),
                ('candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical', models.TextField(blank=True, null=True, verbose_name='Technical Skills')),
                ('soft', models.TextField(blank=True, null=True, verbose_name='Soft Skills')),
                ('project', models.TextField(blank=True, null=True, verbose_name='Project Details')),
                ('language', models.TextField(blank=True, null=True, verbose_name='Language Know')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='documents', verbose_name='Certificate')),
                ('candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidate.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Name')),
                ('titel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Join date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Job discription ')),
                ('candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='candidate.candidateprofile')),
            ],
        ),
    ]
