# Generated by Django 4.2.4 on 2023-09-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_rename_date_candidateprofile_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencedetail',
            old_name='candidate_name',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='skilldetail',
            old_name='candidate_name',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='studydetail',
            old_name='candidate_name',
            new_name='candidate',
        ),
    ]
