# Generated by Django 4.2.4 on 2023-09-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidateprofile_profile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedetail',
            name='resume',
            field=models.FileField(blank=True, default='None', null=True, upload_to='documents'),
        ),
    ]
